### PR TITLE
Adding in better formatted data.

### PR DESCRIPTION
**Pull request by justinmwarner**
Two JSON files:
One with ingredient Id to Ingredient name, type, detail, id.
One with recipe name, book, and page to array of ingredient ids with book and page

### CODE REVIEW

**Comment by justinmwarner** [comment]
@ThomasWFord care to take a look? I spent a weekend cleaning up the data and spent this week exporting it in a some-what okay format.

If you have a better idea to format it, please let me know.  I had to make it `<recipe_name>__<book>__<page> `because some dupes of recipe names (ie: Blood and Sand).

I also removed some of the accents on the ingredients/recipes. I tried to keep them though. It's encoded in utf-8.

I didn't incorprate it with your app, but this should be pretty easy to consume, and may make it a bit quicker =).

**Comment by justinmwarner** [comment]
Also, just an fyi. I may be consuming this myself to make some mobile apps using React Native. If you have any interest, let me know.

**Comment by ThomasWFord** [comment]
Wow this is fantastic! My biggest gripe with what I'd made so far was the duplicate / inconsistent ingredients so I'll definitely look to incorporate this over the next few days, great work!

**Comment by ThomasWFord** [comment]
Got this integrated no problem and the data looks clean, trimmed the ingredients list down by 344 (947 -> 603) when viewing all of the indexes!

**Comment by ThomasWFord** [comment]
Actually the recipes are not matching up with the ingredient IDs correctly, if I look at the Aviation in PDT for example:



The first ingredient listed is 1129 which equals Parsley in the ingredients file:



So the Aviation on the frontend looks like this:



@justinmwarner any ideas, are the IDs out of sync or am I interpreting the file wrong?

**Comment by justinmwarner** [comment]
@ThomasWFord let me take a look this week. I'll send another PR when I get some time!

**Comment by justinmwarner** [comment]
This is strange.  I just ran my Python script again and the output is fine.  Then I compared the two files (the one here and the one that the script generated) and I see every item is different... I honestly have no idea what happened here.

Take a look at my other PR with the updated json files.

**Comment by justinmwarner** [comment]
Diff link: https://www.diffchecker.com/nXVjNwff (should be good for a month)

**Pull request merged**
