### PR TITLE
Update the json files for data source again.

### PR DESCRIPTION
**Pull request by justinmwarner**
So sorry Thomas.  I'll repeat some of what I mentioned in the original PR.

Here's a diff: https://www.diffchecker.com/nXVjNwff

I'm not sure how every single item got changed. I just ran the Python script again and it seems to be clean now.

### CODE REVIEW

**Comment by justinmwarner** [comment]
Also, these are formatted. Please let me know if you prefer no whitespace for size. I can change that out very quickly.

**Comment by phlash13** [comment]
Care to share your Python script?
I've recently checked the PDT recipes and found all of them are missing the ingredient "Syrup, Simple" and I also found 1 or 2 cocktails missing completely, a few were also missing ingredients.
I can try to attach my corrected .csv here once I get home...

**Comment by justinmwarner** [comment]
So, I actually scrubbed all the data myself in an excel file. Then exported that as a unicode CSV. Then I wrote a Python script to process that.  The Python script is pretty small, so I'll post it here, but it's not like the Python script uses the csv files part of this project.  And I can upload that as well if interest. 


```python
class Serializable(dict):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # hack to fix _json.so make_encoder serialize properly
        self.__setitem__('dummy', 1)

    def _myattrs(self):
        return [
            (x, self._repr(getattr(self, x)))
            for x in self.__dir__()
            if x not in Serializable().__dir__()
        ]

    def _repr(self, value):
        if isinstance(value, (str, int, float, list, tuple, dict)):
            return value
        else:
            return repr(value)

    def __repr__(self):
        return '<%s.%s object at %s>' % (
            self.__class__.__module__,
            self.__class__.__name__,
            hex(id(self))
        )

    def keys(self):
        return iter([x[0] for x in self._myattrs()])

    def values(self):
        return iter([x[1] for x in self._myattrs()])

    def items(self):
        return iter(self._myattrs())
class Recipe:
    name = ''
    page = -1
    book = ''
    ingredients = []
import hashlib

class IngredientDetail(Serializable):
    name = ''
    type = ''
    ingredient = ''
    id = -1

    def __hash__(self):
        return hash(self.name)

cocktails = {}
cocktailToBookPage = {}
allTypes = set()
allIngredients = set()
allDetails = set()
import json
import codecs

import csv
f = codecs.open('CocktailRecipesAndIngredients.txt', encoding='utf-16')
for line in f:
    split = line.replace('\r\n', '').replace('\"', '').split("\t")
    cocktail = split[0]
    type = split[1]
    ingredient = split[2]
    detail = split[3]
    page = split[4]
    book = split[5]
    ingredientDetail = IngredientDetail()
    ingredientDetail.name = detail
    ingredientDetail.type = type
    ingredientDetail.ingredient = ingredient
    allDetails.add(ingredientDetail)
    cocktailKey = cocktail + "__" + book + "__" + page
    if cocktailKey in cocktails:
        cocktails[cocktailKey ].append(ingredientDetail)
    else:
        cocktails[cocktailKey ] = [ingredientDetail]
        cocktailToBookPage[cocktailKey ] = [ book, page ]
# Populate the detail -> Id dictionary
detailToId = {}
idToDetail = {}
currId = 0
for detail in allDetails:
    detail.id = currId
    detailToId[detail.name] = currId
    idToDetail[currId] = detail
    currId += 1
recipes = {}
for cocktail in cocktails:
    ingredientIds = []
    splitted= cocktail.split("__")
    for detail in cocktails[cocktail]:
        ingredientIds.append(detailToId[detail.name])
    recipes[cocktail] = [ingredientIds, cocktailToBookPage[cocktail]]

print ("Ingredient Id to Ingredient")
print(json.dumps(idToDetail, ensure_ascii=False).encode('utf-8').decode('utf-8'))
print ("Recipe Name to Array of Ingredient Ids")
print(json.dumps(recipes, ensure_ascii=False).encode('utf-8').decode('utf-8'))
```

**Comment by justinmwarner** [comment]
@phlash13 are you talking about the dataset here, the dataset I have a PR for, or the data in the book?

**Comment by phlash13** [comment]
I'm talking about the .csv file which is missing data from the book - you can simply checking for yourself with any cocktail that includes simply syrup.

**Comment by justinmwarner** [comment]
@phlash13 I don't think this relates to this PR then. I think if you would like to add more complete data, then go on ahead and make a PR to remedy that.  I personally only own one of the books this project is for, so I can't really fill in the gaps myself. I'm sure Thomas would also appreciate more accurate data. 

This PR is specific to cleaning up the data and making it more consistent. IE: We shouldn't have "Syrup, Cane Sugar" and "Simple Syrup" because these are essentially the same. Also making the data a bit more usable and consolidated to one file rather than several.  I also saw that some of the datasets didn't include all the columns others did (ie: vs_and_fc didn't have "ingredient detail" info)

**Pull request closed without merging**
